Content:
    - ${MOOSE_DIR}/framework/doc/content
    - doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        active: True
        name: Aurora App
        repo: https://github.com/aurora-multiphysics/aurora
        home: https://aurora-multiphysics.github.io/aurora/
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include