on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: BuildTestUbuntu
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v2
      # Now build in a container with all deps
      - name: PrintGithubRef
        run: echo $GITHUB_REF
      - name: DockerBuildTest
        run: docker build -t ci-aurora-ubuntu --build-arg build_git_sha=$GITHUB_REF docker/aurora-ubuntu/
