name: PeriodicBuild
on:
  push:
    branches:
      - 20-periodic-ci

  #schedule:
  #  branches:
  #    - main
  #  # Cron syntax has five fields separated by a space, and each field represents a unit of time.
  #  # Min hour day-of-month month day-of-week
  #  - cron: '0 12 * * 1'

jobs:
  build-moose-ubuntu:
    runs-on: ubuntu-20.04
    name: DockerBuildPushBase
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Login
        uses: docker/login-action@v2
        with:
          username: helenbrooks
          password: ${{ secrets.DOCKERHUB_SECRET }}

      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@v4
      #  with:
      #    images: sdixonukaea/achlys-ubuntu

      #- name: BuildPush
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    tags: helenbrooks/aurora-base-ubuntu:github_workflow_${{ github.run_id }}
      #    file: docker/aurora-base-ubuntu/Dockerfile

      # - name: DockerBuildPushMooseUbuntu
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: helenbrooks/moose-ubuntu:github_workflow_${{ github.run_id }}
      #     file: docker/moose-ubuntu/Dockerfile
      #     build-args: |
      #       base_image_tag=github_workflow_4225038104
      #       compile_cores=2

      - name: DockerBuildPushAuroraDepsUbuntu
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: helenbrooks/aurora-deps-ubuntu:github_workflow_${{ github.run_id }}
          file: docker/aurora-deps-ubuntu/Dockerfile
          build-args: |
            base_image_tag=latest
            compile_cores=2

       # - name: DockerBuildPushAuroraUbuntu
       #   uses: docker/build-push-action@v4
       #   with:
       #     context: .
       #     push: true
       #     tags: helenbrooks/aurora-ubuntu:github_workflow_${{ github.run_id }}
       #     file: docker/aurora-ubuntu/Dockerfile
       #     build-args: |
       #       base_image_tag=github_workflow_${{ github.run_id }}
       #       compile_cores=2